### ISSUE TITLE
It's just impossible to deploy using amazon-eks-entrypoint-new-vpc.template.yaml

### ISSUE THREAD

**Issue by moophlo** [aws-quickstart/quickstart-amazon-eks#402] opened 2022-03-21 11:43 UTC
It's been 3 weeks I'm trying hard to deploy and EKS cluster in a new VPC with Rancher installation. It's just impossible, I'm getting each time a new error, first semantic_version error (solved with custom quickstart patched with semantic_version=2.8.5), then a generic internal error on RBAC creation, now internal error in EKS creation. I'm doing nothing exotic, using default settings for everything but stack and cluster name, enabling CALICO and RANCHER, period. No way. An also 99% of the times rollback doesn't work and does not delete all resources completely, so i do have to go and find out what and where something have been created to remove and start over. Someone did have success deploying using this templates or they're just cosmetic?

**Comment by moophlo** [comment] 2022-03-21 13:47
Trying again, now I'm stuck on Amazon-EKS-EKSStack-XXXXXXXXXXX-EKSControlPlane-XXXXXXXXXX with "EKS	CREATE_IN_PROGRESS" ... but does not show "Resource creation Initiated" ... In the EKS console nothing appears ... in the other tries the EKS cluster and the nodes group did create correctly ... now nothing

**Comment by moophlo** [comment] 2022-03-22 08:22
Solved the "EKS CREATE_IN_PROGRESS" stuck in progress with manual re-creation of roles: awsqs-eks-cluster,
awsqs-kubernetes-get,awsqs-kubernetes-helm,awsqs-kubernetes-resource. Now i hint again #401 ... as I said ... no way out ... one problem after the other. What I think is missing here is a way to clean up correctly after failure

**Comment by moophlo** [comment] 2022-03-22 09:23
Now "The following resource(s) failed to create: [SSMWaitCondition]." it fails because TempRancherInstance get terminated!!!

**Comment by jency92** [comment] 2022-03-28 04:49
same issue im also facing, any workaround?

**Comment by troy-ameigh** [comment] 2022-04-01 20:55
To be clear even on role back the Account and Region Shared Resource templates will not be removed on rollback, however as long as you leave those parameters in "AutoDetect" It will find them and reuse them. If you truly want to clean your account you can do the following, however it will destroy and cluster stood up with the QS, so becareful. 

1. Clone the repo to your local machine, then run the following. 
2. $> PROFILE=<AWS Profile> make clean-aws

**Comment by DelDennis** [comment] 2022-04-02 20:14
Im also getting a generic "Internal Failure" in the control plane stack. Ive gone through the deleted stacks and see nothing to hint at the cause of the problem.

**Comment by troy-ameigh** [comment] 2022-04-08 17:59
Resolved Closing

**Closed by troy-ameigh** 2022-04-08 17:59 UTC
