### ISSUE TITLE
EKS Stack - No transform named 682804326264::QuickStartParameterResolver found

### ISSUE THREAD

**Issue by jonf-78** [aws-quickstart/quickstart-amazon-eks#259] opened 2020-12-02 21:54 UTC
Hi,

Great project.

I am running a deployment and am hitting this issue: 

Amazon-EKS-EKSStack-1PI543GBG7A1/4d573c90-34e5-11eb-8042-0a05df596088 was not successfully created: No transform named 682804326264::QuickStartParameterResolver found.

I am defaulting everything except enabling EFS, also tried with disabled EFS and see the same issue, I have an existing stack deployed.

Has anyone experienced this before as from debugging I cant see too much else output ?

Thanks
Jon

**Comment by jaminbern** [comment] 2020-12-30 16:45
for anyone coming across this issue - the problem is with the 'shared resources' that are now part of this build. They didn't exist 3 months ago. So - even if you built this prior to 30 September (maybe sooner - I didn't really look through the history to see when this merged in) you still need to say 'Yes' to the   PerAccountSharedResources and  PerRegionSharedResources.

Once you've built them - I guess you don't need to build them again... But - what happens when the developers change these? I'm not sure the whole 'shared resource' in a cloudformation - has been completely thought through here (its fine if you are developing for your own stuff - but for a generic AWS Quick-Start I see it causing issues - like it did for me here...)

**Comment by mayaeger** [comment] 2021-01-13 15:29
I also am hitting this issue when trying to deploy into a VPC with an existing cluster.  The form and the docs are very specific about saying 'No' to the Shared Resources in that specific circumstance.

So thanks for posting, I'll have to see if I can go down the path of what setting that to 'Yes' would be.

**Comment by jaminbern** [comment] 2021-01-13 16:07
Firstly - I just want to say me comments are not intended to be judgmental -there are some small errors here that caused me some (small) pain - and caused me to have to work out what some parts of the cfn do....

I'm very grateful that this project exists - and it has helped me hugely - saving hundreds of hours of dev time!

@mayaeger - As you can imagine - I was concerned about this - but fortunately I was building a new cluster (the old was still running though).

My research suggested it just creates a bunch of lambda functions (and a a couple of CFN macro's - which is where the bug comes from - their lack of existence causes the CFN to choke). I'm guessing these weren't used previously and/or the lambda functions were - but were created each time the CFN was run. I don't see why creating them again is a problem - and as I stated - if these are updated - then this could further cause issues. But - I do see that the devs are trying to automate if these are or aren't created - so that could be their solution.

Thanks!

**Comment by jaymccon** [comment] 2021-01-13 20:45
We've completed adding a new option `AutoDetect` for shared resources, so one does not need to know in advance whether they are deployed or not. Stack updates, or new stacks in an account with the resources already existing will update shared resources to keep up to date with big fixes. This means that we have to consider backwards compatibility carefully with the shared resources,  but that's an ok trade-off imho.

Thanks for the encouragement @jaminbern

**Comment by mayaeger** [comment] 2021-01-15 14:24
Thanks @jaymccon and @jaminbern, appreciate the responses!

**Comment by snowake4me** [comment] 2021-03-03 03:56
I bumped into this, as well - and alas, I _started_ with AutoDetect.  Unfortunately, we have some SCPs at the Organization level that block access to certain regions -- and this causes something within the AutoDetect process to fail (specifically, I get a failure on performing "DescribeStacks" in one of the restricted regions).  So - next, as above, I tried answering "No" to Shared Resources - and it failed because of the missing transform.

Off to try it again - this time, saying Yes to the Shared Resources!

Sharing the encouragement, appreciation, respect and gratitude for the 'accelerant' and learning this project provides.  Thank, @jaymccon  and **all** contributors!

**Comment by koogled** [comment] 2021-03-04 15:28
Can anyone explain what the transform [QuickStartParameterResolver] does.  I am going to use this template in a non-interactive environment and provide the parameters using a wrapper CFN template.  
So rather that trial and error, I'd like to remove the transform and pre-empt any problems the transform removal might cause.
Thanks in advance

**Closed** 2022-01-20 21:01 UTC
