### ISSUE TITLE
worker nodes are not joining the cluster

### ISSUE THREAD

**Issue by maguire007** [aws-quickstart/quickstart-amazon-eks#7] opened 2019-02-18 12:19 UTC
I executed the template twice and got the same result in us-west-2.  None of the worker nodes seem to be joining into the cluster.

from the bastion: 
kubectl get nodes
No resources found.

All the node instances are created and running.  The config looks right. 

This was created with the new vpc option.

**Comment by maguire007** [comment] 2019-02-18 12:56
Some more debugging:
The kubelet is running on the node but failing to register the node.

Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:09.118312    4015 kubelet_node_status.go:79] Attempting to register node ip-10-0-1-229.us-west-2.compute.internal
Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:09.276627    4015 kubelet_node_status.go:103] Unable to register node "ip-10-0-1-229.us-west-2.compute.internal" with AP


Full Logs:

sudo systemctl status kubelet -l
journalctl -xeu kubelet


● kubelet.service - Kubernetes Kubelet
   Loaded: loaded (/etc/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubelet-args.conf
   Active: active (running) since Mon 2019-02-18 02:59:45 UTC; 9h ago
     Docs: https://github.com/kubernetes/kubernetes
  Process: 3999 ExecStartPre=/sbin/iptables -P FORWARD ACCEPT (code=exited, status=0/SUCCESS)
 Main PID: 4015 (kubelet)
    Tasks: 20
   Memory: 112.0M
   CGroup: /system.slice/kubelet.service
           └─4015 /usr/bin/kubelet --cloud-provider aws --config /etc/kubernetes/kubelet/kubelet-config.json --allow-privileged=true --kubeconfig /var/lib/kubelet/kubeconfig --container-runtime docker --network-plugin cni --node-ip=10.0.1.229 --pod-infra-container-image=602401143452.dkr.ecr.us-west-2.amazonaws.com/eks/pause-amd64:3.1

Feb 18 12:44:28 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:28.935298    4015 kubelet_node_status.go:103] Unable to register node "ip-10-0-1-229.us-west-2.compute.internal" with API server: Unauthorized
Feb 18 12:44:28 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:28.935364    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:44:29 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:29.229253    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
Feb 18 12:44:29 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:29.229315    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
Feb 18 12:44:30 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:30.122375    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:44:30 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:30.366600    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized
Feb 18 12:44:30 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:30.366651    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
Feb 18 12:44:31 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:31.277944    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:44:31 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:31.505886    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauthorized
Feb 18 12:44:31 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:44:31.505979    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthorized




journalctl -xeu kubelet

Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:09.112211    4015 kubelet_node_status.go:332] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/r
Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:09.118312    4015 kubelet_node_status.go:79] Attempting to register node ip-10-0-1-229.us-west-2.compute.internal
Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:09.276627    4015 kubelet_node_status.go:103] Unable to register node "ip-10-0-1-229.us-west-2.compute.internal" with AP
Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:09.491087    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:09.658346    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:09 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:09.658382    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:10 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:10.715016    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:10 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:10.890504    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:10 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:10.890535    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:11 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:11.871992    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:12 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:12.040123    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:12 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:12.040123    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:13 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:13.021483    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:13 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: W0218 12:46:13.141589    4015 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Feb 18 12:46:13 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:13.142141    4015 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady 
Feb 18 12:46:13 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:13.192066    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:13 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:13.192122    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:14 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:14.171311    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:14 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:14.342364    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:14 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:14.342389    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:15 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:15.324447    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:15 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:15.487245    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:15 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:15.487340    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:16.276849    4015 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:16.276885    4015 kubelet_node_status.go:317] Adding node label from cloud provider: beta.kubernetes.io/instance-type=t3
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:16.276895    4015 kubelet_node_status.go:328] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/z
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:16.276901    4015 kubelet_node_status.go:332] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/r
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:16.282484    4015 kubelet_node_status.go:79] Attempting to register node ip-10-0-1-229.us-west-2.compute.internal
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:16.432412    4015 kubelet_node_status.go:103] Unable to register node "ip-10-0-1-229.us-west-2.compute.internal" with AP
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:16.432478    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:16.626065    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:16 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:16.626064    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:17 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:17.575906    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:17 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:17.766742    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:17 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:17.766811    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:18 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: W0218 12:46:18.143208    4015 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Feb 18 12:46:18 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:18.143390    4015 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady 
Feb 18 12:46:18 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:18.335567    4015 eviction_manager.go:243] eviction manager: failed to get get summary stats: failed to get node info: n
Feb 18 12:46:18 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:18.730559    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:18 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:18.909718    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:18 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:18.909749    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:19 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:19.885951    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:20 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:20.079912    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:20 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:20.079930    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:21 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:21.042119    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:21 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:21.236812    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:21 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:21.236832    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:22 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:22.204222    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:22 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:22.436451    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:22 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:22.436525    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: W0218 12:46:23.144370    4015 cni.go:172] Unable to update cni config: No networks found in /etc/cni/net.d
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:23.144518    4015 kubelet.go:2110] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady 
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:23.361644    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:464: Failed to list *v1.Node: Unauthorized
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:23.432592    4015 kubelet_node_status.go:269] Setting node annotation to enable volume controller attach/detach
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:23.432623    4015 kubelet_node_status.go:317] Adding node label from cloud provider: beta.kubernetes.io/instance-type=t3
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:23.432630    4015 kubelet_node_status.go:328] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/z
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:23.432635    4015 kubelet_node_status.go:332] Adding node label from cloud provider: failure-domain.beta.kubernetes.io/r
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: I0218 12:46:23.437247    4015 kubelet_node_status.go:79] Attempting to register node ip-10-0-1-229.us-west-2.compute.internal
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:23.581741    4015 kubelet_node_status.go:103] Unable to register node "ip-10-0-1-229.us-west-2.compute.internal" with AP
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:23.581834    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:455: Failed to list *v1.Service: Unauthoriz
Feb 18 12:46:23 ip-10-0-1-229.us-west-2.compute.internal kubelet[4015]: E0218 12:46:23.593169    4015 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Unauth
lines 941-1001/1001 (END)

**Comment by jaymccon** [comment] 2019-02-18 18:52
looks like this regression was introduced in  ac37254 . From what I can see when the yaml library in use decides to use the alternative list format (`[ value ]`) instead of (`- value`) that iam authenticator fails to paerse the config.

Fix incoming.

**Comment by maguire007** [comment] 2019-02-18 20:46
Cool.  I see the commit.  Are they deployed on the quick start s3 site yet?  I'll test it out when its deployed.

**Comment by jaymccon** [comment] 2019-02-18 20:46
fixed in 3c83499, should be in s3 now

**Closed by jaymccon** 2019-02-18 20:46 UTC

**Comment by maguire007** [comment] 2019-02-18 21:04
I tried to startup a new cluster but it failed and rolled back.  I am going to startup another to try to repeat it.

This is the error i got.  


Embedded stack arn:aws:cloudformation:us-east-2:<>>>>:stack/Amazon-EKS-EKSStack-1QSRRJ8ZFBIQX/22b30b00-33bf-11e9-ba44-0626229bfdda was not successfully created: The following resource(s) failed to create: [IamStack].

**Comment by maguire007** [comment] 2019-02-18 21:10
looks like the above issue was due to not clicking the agreement steps. at the end of the CF.

I acknowledge that AWS CloudFormation might create IAM resources with custom names.
I acknowledge that AWS CloudFormation might require the following capability:

**Comment by maguire007** [comment] 2019-02-18 21:35
Confirmed the fix worked.  Thanks!

kubectl get nodes
NAME                                        STATUS    ROLES     AGE       VERSION
ip-10-0-13-225.us-east-2.compute.internal   Ready     <none>    5m        v1.11.5
ip-10-0-39-165.us-east-2.compute.internal   Ready     <none>    5m        v1.11.5
ip-10-0-95-111.us-east-2.compute.internal   Ready     <none>    5m        v1.11.5
