### ISSUE TITLE
Deploy SSL into Jenkins URL via cft

### ISSUE THREAD

**Issue by Srikanth1992** [aws-quickstart/quickstart-amazon-eks#346] opened 2021-07-23 08:05 UTC
Hi Team,

I’m trying to use your quick start guide templates to set up cloudbees ci in my environment.

I’m using this template( https://github.com/aws-quickstart/quickstart-cloudbees-ci/blob/main/templates/cloudbees-ci-workload.template.yaml ) to deploy jenkins into an existing cluster.

After jenkins set up I’m looking to deploy ssl Certs into jenkins url via cloudformation template but this quick start guide doesn’t provide that template.

cloudbees has ssl steps from below link which cannot be automated via cft. Do you have any way deploy ssl certs using cft please let me know
https://docs.cloudbees.com/docs/cloudbees-ci/2.235.2.3/cloud-admin-guide/kubernetes-self-signed-certificates#_installing_self_signed_certificates_on_kubernetes

**Comment by tlindsay42** [comment] 2023-02-10 22:21
Closing as duplicate of https://github.com/aws-quickstart/quickstart-cloudbees-ci/issues/44

**Closed by tlindsay42** 2023-02-10 22:21 UTC
Labels: duplicate, question
